[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]
aptPkgs = ["python", "make", "g++"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"